on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Executables
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        # https://github.com/marketplace/actions/setup-go-environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version: '1.19'

      - name: Build for Darwin
        run: scripts/build.sh darwin
      - name: Build for Windows
        run: scripts/build.sh windows

      - name: Upload Artifacts
        # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executables
          path: build
